### ISSUE TITLE
typecheck-tests is at 155 errors / 48 files and growing — fix the ServiceToken shape and put it in CI

### ISSUE THREAD

**Issue by sroussey** [PodleyAI/sec#321]
The script is not in CI and the documented count is three measurements stale.

| when | errors |
|---|---|
| CLAUDE.md (as written) | 122 |
| PR #311, 2026-08-20 | 140 |
| `dd11d316`, today | **155 across 48 files** |

`bun run build` and `bun run test` both pass over these files, so nothing else type-checks them — which is exactly the condition CLAUDE.md describes and then does not act on.

**Dominant shape (~40 of the 48 files, all `src/cli/queries/*.test.ts`):** a test helper hands `ServiceToken<CrowdfundingRepositoryStorage>` where an `ITabularStorage` is expected, so every `.put()` on it errors. One helper fix should clear the bulk.

Others worth separating out:
- `DbStatus.test.ts:143` passes an `updateProgress` mock returning `number` where `void | Promise<void>` is required.
- A `spac_candidate` fixture omits the `signal_filed_sic_6770` column added last window — a **real near-miss**, not a typing artifact.

Plan:
1. fix the helper;
2. sweep the remainder;
3. add `bun run typecheck-tests` to `test.yml` between `format-check` and `build`;
4. update the CLAUDE.md paragraph to say it *is* in CI, rather than describing the conditions under which it would be.

Found during the 2026-08-24 review. Snapshot: `workglow-dev/prd` → `analysis/grades/2026-08-24/sec-detailed.md`.

**Comment by sroussey** [comment]
**Verified at `9a1da01`: 155 → 2. Steps 1, 2 and 4 done; step 3 (CI) is all that remains.**

```
$ bun run typecheck-tests
src/resolver/PersonResolver.race.test.ts(73,3): error TS2719: … Two different types with this name exist, but they are unrelated.
  Types of property 'role_scope' are incompatible.
    Type 'string | null | undefined' is not assignable to type 'string | null'.
src/resolver/PersonResolver.test.ts(47,3): error TS2719: … (same)
exit 2
```

- **Step 1 — the `ServiceToken` shape: fixed.** Zero errors remain in the `src/cli/queries/*.test.ts` family that was ~40 of the 48 files.
- **Step 2 — the sweep: fixed.** The `updateProgress` mock returning `number` is gone; so is the `spac_candidate` fixture missing `signal_filed_sic_6770` — that one was a real near-miss and `de6c5ea` ("test(query): give the person fixture the column its table now requires") is the class of fix.
- **Step 4 — the doc: done.** `CLAUDE.md` now reads "the suite reports 2 errors across 2 files, both the same `TS2719`", which matches the measurement above.
- **Step 3 — CI: not done.** `git log 7cc13dd..origin/main -- .github/` is empty; `.github/workflows/test.yml` is still `bun i` → `format-check` → `build` → `test`.

The two survivors share **one** root cause: `PersonObservation` is reached by two paths whose `role_scope` differs only by `| undefined`, so a single declaration change should clear both. CLAUDE.md's own wording is now the right one — "the count is now close enough that landing it red would be a choice rather than an inheritance" — so this is a one-change issue.

Other checks run for context: `bun run format-check` PASS, `bun run build` (transpile + full `tsc`) PASS, `bunx vitest run` = 4,407 passed / 21 skipped / 2 timeout flakes that both pass green in isolation.

Verified during the 2026-08-31 review.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by sroussey** [comment]
**Fixed, and verified by execution.** Both halves of the ask land: the errors are gone, and the check is in CI.

The separate `typecheck-tests` script is gone because tests are no longer excluded — there is one tsconfig over the whole tree:

```
$ cat tsconfig.json
{
  // One config for the whole tree, tests included. There is no declaration
  // emit to protect any more … `tsc --noEmit` is the only thing tsc is asked to do.
  "include": ["src/**/*", "scripts/**/*"],
  …
}
$ node -e 'console.log(require("./package.json").scripts.typecheck)'
tsc --noEmit
```

Run against `origin/main` (`2ab82ba`) after a clean `bun install`:

```
$ bun run typecheck
$ tsc --noEmit
EXIT=0
```

**Zero errors across `src` + `scripts`, tests included** — down from the 155 / 48 files this issue was filed at and the 2 / 2 `TS2719` it was carried at last cycle. The `ServiceToken` shape that caused both is gone with the identity tier (`defe9b7`).

And it is in CI, third of five steps:

```
$ grep -n 'run: bun run' .github/workflows/test.yml
      - run: bun run format-check
      - run: bun run lint
      - run: bun run typecheck
      - run: bun run build
      - run: bun run test
```

For completeness, the rest of that pipeline is green here too: `format-check` (835 files), `lint` (oxlint + tsgolint type-aware, exit 0), `build`, and `vitest run` — **145 test files passed, 3 skipped; 1,429 tests passed, 21 skipped; 284s**.

Closing as `completed`.

---
_Generated by [Claude Code](https://claude.ai/code)_
