### PR TITLE
fix(s1): classify throttle exhaustion transiently, let Ctrl-C through, store captions verbatim

### PR DESCRIPTION
**Pull request by sroussey**
Stacked on #251 — base is `claude/testing-structure-improvements-i7p0qq`, not `main`. Review #251 first; this branch only adds to it.

### 1. An exhausted throttle budget dead-lettered version-gated (HIGH)

When `MAX_RATE_LIMIT_WAITS` was spent, `runGuardedExtraction` fell through to `attempt++` and the 429 propagated as a plain error, which `runSection` mapped to `MODEL_INVALID_OUTPUT`. That code is not in `MODEL_ERROR_REASON_CODES`, so recovering from a transient quota condition required bumping the extractor version and re-running.

New `RATE_LIMITED` reason code, added to both `DEAD_LETTER_REASON_CODES` and `MODEL_ERROR_REASON_CODES`, plus an exported `RateLimitExhaustedError` thrown once the budget is spent (carrying the provider text and the original error as `cause`).

**Why a new code rather than reusing `MODEL_RESOLUTION_ERROR`.** Their retry semantics are identical — both stay eligible under the same version — but they are not the same fact. `MODEL_RESOLUTION_ERROR` means the configured model id is not registered or is misconfigured, and its operator action is *add a key / register a provider*. A spent throttle budget means *wait for the quota window, then retry*. Merging them makes the worklist counts unreadable during exactly the outage you would be triaging: a page of "model unavailable" entries when nothing about the model configuration is wrong.

### 2. Ctrl-C during a throttle wait was swallowed (HIGH)

The abort branch threw `lastError` (the 429), not a `TaskAbortedError`. `runSection` recorded `MODEL_INVALID_OUTPUT` and **returned normally**, so nothing reached the `storeError instanceof TaskAbortedError || context.signal?.aborted` guard in `ProcessAccessionDocFormTask` — the remaining sections of an interrupted filing all ran and dead-lettered the same way. That violates the cooperative-cancellation invariant CLAUDE.md states explicitly.

- `runGuardedExtraction` now throws `TaskAbortedError` on abort.
- `makeRunSection` takes an optional `signal`, threaded from `args.context?.signal` at every call site.
- `runSection`'s catch is ordered: rethrow a `TaskAbortedError`; then, if the signal is already aborted, rethrow as `TaskAbortedError` preserving the original as `cause`; only then map to a reason code.

Neither branch can swallow a real failure: the first keys on the error **type**, so a genuine schema failure is never rethrown by it, and the second only fires when the signal is already aborted — a state in which `ProcessAccessionDocFormTask` abandons the filing regardless.

**`runSection`'s contract changed from "never throws".** What I found at the wrapping call sites:

| call site | wraps `runSection`? | verdict |
| --- | --- | --- |
| `loi8k.ts` | yes — `catch (err) { recordLoiRun(false, message); throw err; }` | **rethrows**, does not swallow |
| `redemption8k.ts` | yes — same shape with `recordRedemptionRun` | **rethrows**, does not swallow |
| `Form_DEFM14A.storage.ts` | yes — same shape | **rethrows**, does not swallow |
| `Form_S_1.storage.ts` / `Form_424.storage.ts` | no wrapping try/catch | propagates |

The two 8-K paths do record a *failed extractor run* before rethrowing. That is correct rather than a leak: a failed run row makes the ordinary forms sweep re-select the filing, which is what an interrupted filing wants, and it stamps no version-gated dead letter.

`signal` is threaded at all seven `makeRunSection` call sites (the five named plus `Form_424.storage.ts` and `Form_DEFM14A.storage.ts`, which share the runner and had the same exposure).

### 3. The 429 matcher misfired in both directions (MEDIUM)

`/(?<[\w.,])429(?[\w.,])/` accepted stack frames and rejected real statuses. Replaced with a matcher that requires the surrounding word, applied only to the **head of the message** (everything before the first newline) so an appended `.stack` cannot reach it. The phrase matcher (`rate limit` / `too many requests`) is scoped to the head for the same reason — a stack frame reading `at isRateLimitError` matched it otherwise.

Accept / reject table, all pinned as a table-driven test:

| accepted | rejected |
| --- | --- |
| `429 Too Many Requests` | `at extract (/a/sectionExtractors.ts:429:15)` |
| `HTTP 429` | `Invalid value: expected string, got 429` |
| `HTTP/1.1 429 Too Many Requests` | `Invalid value for "shares_owned": 1,429,000` |
| `Request failed with status code 429.` | `expected a number, got $429.50` |
| `{"status":429,"message":"x"}` | `schema validation failed at row 4290` |
| `{"code":429}` | `tokens 4290` |
| `Error 429: rate limited` | `expected 429 rows` |
| `status: 429` | a schema failure carrying an appended stack with `sectionExtractors.ts:429:15` |
| `AI_APICallError: status 429` | |

One deviation from the reviewed list: `Rate limit... 1,429,000` is **accepted**, and the test says so. It contains the phrase "Rate limit", so it really is a throttle message; only the *digits* must not carry the decision, which the share-count case above covers.

### 4. The stated-delay parser could not read what providers emit

`/([\d.]+)\s*s/` did not match OpenAI's real RPD phrasing `Please try again in 8m38.4s` — it returned `null`, the caller fell back to a 1s exponential base, and five waits totalled 1+2+4+8+16 = 31 seconds against a limit measured in minutes.

New exported `statedDelayMs` parses composite durations (`ms` before `m`) and sums them: `8m38.4s`→518400, `4.082s`→4082, `1h`→3600000, `90s`→90000, `2m`→120000, `1h30m5s`→5405000, `500ms`→500, no stated delay→`null`. The `+250` margin and the `MAX_RATE_LIMIT_WAIT_MS` clamp are unchanged.

One correction to the reviewed expectations: the plan asked for `rateLimitWaitMs("90s")` ⇒ `90_250`, which cannot hold — `MAX_RATE_LIMIT_WAIT_MS` is 30 000 and clamps it, as it does the `1h` and `2m` cases in the same list. The parser is tested directly for `90s` ⇒ `90_000`, and `rateLimitWaitMs` is tested for the clamp.

### 5. Risk-factor headlines were stored truncated (MEDIUM)

`Form_S_1.storage.ts` stored `contiguousSpanHead(r.headline ?? "")`, but `RiskFactorSchema` and CLAUDE.md both document `headline` as the filer's caption **verbatim**. A caption containing `...`/`…` was persisted as a partial sentence with no marker: the head verified, `worstVerdict` returned `ok`, and `markResolved` cleared the section — no dead letter, no `-partial` entry.

The salvage rationale is about *citations* and still applies to `source_span` via `boundSourceSpan`. It does not apply to the row's payload. `verifyRow` now rejects an elided headline before verdict-merging (`isElided`, exported from `verifySourceSpan.ts`), so the row drops into the existing `-partial` / `UNVERIFIED_SOURCE_SPAN` machinery, and `persist` stores `r.headline.trim()` whole.

**Extractor version bump required.** `UNVERIFIED_SOURCE_SPAN` is version-gated, so filings whose captions were stored truncated only become retry-eligible after an S-1 version bump. That is **not a code change** — extractor versions live in the `component_versions` table, seeded at `1.0.0` by `bootstrapComponentVersions()` and moved only by the CLI ceremony. Nothing in this diff can do it. The deploying operator runs:

```sh
sec version start-dev extractor S-1 <next-semver> --bump minor
sec version promote extractor S-1        # announces how many dead-letters became eligible
sec extractor retry-dead-letters S-1
```

### 6. Reproducibility table counted un-measured fixtures (MEDIUM)

`summarizeStability` excludes a fixture that did not complete all `runs` repetitions from `stableExact`/`stableContent`, but `fixtures` still counted it, so an interrupted sweep printed `same 3/5` — reading as "two measured and unreproducible" when they were never measured twice. Added `measured`, kept `fixtures` as the total, and the table now prints `stableExact/measured` with `(N skipped)` appended when nonzero.

## Rebase prerequisite for #251

#251 is 10 commits behind `origin/main` and needs rebasing before merge. Its `src/cli/groups/eval.ts` hunk contradicts main and CLAUDE.md: the rewritten `DEFAULT_MODELS` JSDoc claims "a missing key is recorded as a failed run per fixture rather than aborting the sweep", while main implements key-based filtering (`availableDefaultModels`) and CLAUDE.md documents defaults as "skipped with a warning". Since this branch stacks rather than rebases, that comment hunk is reverted here to main's text; the rest of the eval.ts divergence is main being ahead and resolves on the rebase.

Related: main has since added `UNVERIFIED_SOURCE_SPAN`, `SOURCE_SPAN_TOO_LONG` and `MIXED_CAPTION_SHAPE` to `DEAD_LETTER_REASON_CODES` and typed `DeadLetterInput.reason_code` to that union, plus the CLAUDE.md vocabulary paragraph listing them. `RATE_LIMITED` is added to the list as it exists on this base; the rebase merges the two additions and `RATE_LIMITED` should join that documented vocabulary list at the same time.

## Tests

- `rateLimitBackoff.test.ts` converted to `vi.useFakeTimers()` driven by `advanceTimersByTimeAsync`: 11 tests / 3.45s of real sleeping → 41 tests / 0.14s. The fictional `"try again in 3600s"` case (no provider emits it, and the old parser ignored it, so the cap it named was never exercised) is replaced by the real `8m38.4s` phrasing plus the `1h` / `2m` / `90s` / `500ms` cases.
- Table-driven `isRateLimitError` over the full accept/reject table, including the appended-stack case.
- `sectionExtractors`: a provider that always throttles rejects with `RateLimitExhaustedError`; aborting the signal mid-wait rejects with `TaskAbortedError` and the provider is not called again.
- `sectionRunner.test.ts`: `RateLimitExhaustedError` ⇒ `RATE_LIMITED`; `TaskAbortedError` ⇒ rejects with no dead-letter row; a plain `Error` under an aborted signal ⇒ rejects as `TaskAbortedError` (original preserved as `cause`), no row; a plain `Error` with nothing aborted ⇒ still `MODEL_INVALID_OUTPUT`.
- `Form_S_1.storage.riskfactors.test.ts`: an elided caption with a verifying span ⇒ 0 rows and `UNVERIFIED_SOURCE_SPAN`; a fully verbatim caption ⇒ persisted byte-for-byte.
- `fingerprintRows.test.ts`: one 2-run group and one 1-run group at `runs: 2` ⇒ `{ fixtures: 2, measured: 1, stableExact: 1 }`.
- `ExtractionDeadLetterRepo.test.ts`: a `RATE_LIMITED` entry is eligible under the **same** extractor version while a `MODEL_INVALID_OUTPUT` one is not.

No exhaustiveness `switch` over `DeadLetterReasonCode` exists on this base, so adding the code compiled cleanly; `sec extractor dead-letters` prints `reason_code` as an opaque string and needed no change.

## Verification

Commands run in a clean worktree of this branch, at the pushed commits:

```
npx tsc --noEmit
  → 2 errors, both pre-existing and unrelated (splitName.ts:33, PersonNormalization.ts:101,
    'suffix' does not exist on type 'ParsedName'); byte-identical on the base commit.

npx vitest run src/resolver src/sec/forms          → 93 files, 834 tests passed
npx vitest run src/sec/forms/registration-statements src/storage/dead-letter
                                                   → 45 files, 400 tests passed
npx vitest run src/eval src/sec/forms/miscellaneous-filings
               src/sec/forms/proxies-information-statements
                                                   → 16 files, 149 tests passed
npx vitest run src/cli --maxWorkers=2              → 29 files, 288 tests passed
```

Honest note on the first attempt: running `src/eval src/sec/forms/miscellaneous-filings src/sec/forms/proxies-information-statements src/cli` together at default concurrency produced 32 failures in `src/cli/groups/{version,canonical,resolve}.test.ts` and `src/eval/{realSections,goldenS1Labels}.test.ts` — all `Test timed out`. The same set fails on the **base commit** under the same load (11 failures), and every one of those files passes in isolation on this branch (`version.test.ts` 12/12, `goldenS1Labels`+`realSections` 10/10). These are subprocess-spawning suites starved under load in this sandbox, not regressions; the numbers above are from runs at a concurrency they survive.

---
🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01K6huUY7hSkRbjun1P9HKsz

---
_Generated by [Claude Code](https://claude.ai/code/session_01K6huUY7hSkRbjun1P9HKsz)_

### CODE REVIEW

**Comment by sroussey** [comment]
Merged the rebased base (`claude/testing-structure-improvements-i7p0qq`) into this branch to clear the conflict — plain two-parent merge at `7623424`, no force-push.

**Why it conflicted:** the base's `728b0a5` is a cherry-pick of this PR's own first commit `1ba3dc1` (identical patch-id), replayed onto a parent that already carried #253. So ~14 hunks conflicted over changes that do not actually disagree. `git diff 728b0a5 <base>` is empty for every conflicted file, so each was rebuilt as `base + git diff 1ba3dc1 3340fde`; three applied cleanly with no manual edit, which is evidence the two changesets are disjoint.

**Hand-resolved:** the `sectionRunner` catch, which #253 and this PR both extend. Order is `TaskAbortedError` → `signal.aborted` (rethrown as `TaskAbortedError`, original as `cause`) → `SecCliConfigurationError` → `NONCE_MISMATCH`/`MIXED_CAPTION_SHAPE`/`RATE_LIMITED`/default. Cancellation precedes the configuration escape because the aborted-signal branch is intentionally type-blind: once cancellation is in flight, whatever a torn-down provider call raises is a teardown artifact rather than a verdict on the section. Both escapes rethrow, so neither can be swallowed in either order — the ordering only decides which error the pipeline observes.

Two test blocks collided textually (both sides appended a different `describe`); both were written out in full. Nothing was deleted or weakened on either side.

**Correction to the verification section above:** it states two pre-existing `tsc` errors in `splitName.ts` / `PersonNormalization.ts`. Those were fixed on the base and are gone — `npx tsc --noEmit` now exits 0. Post-merge: 46 files / 432 tests, 16 / 170, and 30 / 297 across the three suites, all passing, including both changesets' assertions in one run. The subprocess-spawning suites that time out under parallel load in some environments passed here without needing that caveat.

---
_Generated by [Claude Code](https://claude.ai/code)_
